<a href="https://colab.research.google.com/github/hemantmehra/ml_pytorch/blob/master/Pytorch-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

# Basic Autograd Example 1

In [ ]:
x = torch.tensor(10., requires_grad=True)
w = torch.tensor(20., requires_grad=True)
b = torch.tensor(30., requires_grad=True)
x, w, b

(tensor(10., requires_grad=True),
 tensor(20., requires_grad=True),
 tensor(30., requires_grad=True))

In [ ]:
y = w * x + b
y

tensor(230., grad_fn=<AddBackward0>)

In [ ]:
y.backward()
x.grad, w.grad, b.grad

(tensor(20.), tensor(10.), tensor(1.))

# Basic Autograd Example 2

In [ ]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [ ]:
linear = nn.Linear(3, 2)
linear.weight, linear.bias

(Parameter containing:
 tensor([[ 0.0274,  0.2762, -0.0963],
         [-0.3595, -0.2327, -0.1054]], requires_grad=True),
 Parameter containing:
 tensor([0.3090, 0.1895], requires_grad=True))

In [ ]:
for i in linear.parameters():
  print(i)

Parameter containing:
tensor([[ 0.0274,  0.2762, -0.0963],
        [-0.3595, -0.2327, -0.1054]], requires_grad=True)
Parameter containing:
tensor([0.3090, 0.1895], requires_grad=True)


In [ ]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [ ]:
pred = linear(x)
loss = criterion(pred, y)
print('loss at step 0: ', loss.item())
loss.backward()
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)
optimizer.step()
pred = linear(x)
loss = criterion(pred, y)
print('loss at step 1: ', loss.item())

loss at step 0:  1.616817831993103
dL/dw:  tensor([[-0.1027,  0.2951, -0.6354],
        [ 0.0894, -0.5346,  0.1998]])
dL/db:  tensor([0.9812, 0.1341])
loss at step 1:  1.5987653732299805
